simplesocial/myFYP/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'myFYP'
urlpatterns = [
    url(r"^login/$", auth_views.LoginView.as_view(template_name="myFYP/login.html"),name='login'),
    url(r"^vas_login/$", auth_views.LoginView.as_view(template_name="myFYP/vas_login.html"),name='vas_login'),
	url(r'^contact/$',views.contact, name='contact'),
    url(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
	url(r'^addproperty/$',views.addproperty, name='addproperty'),
    url(r'^About-Us/$',views.About.as_view(), name='About-Us'),
    url(r'^services/$',views.Services.as_view(), name='Our-Services'),
    url(r'^nointernet/$',views.Nointernet.as_view(), name='nointernet'),
    # url(r'^main_login/$',views.Main_login.as_view(),name='main_login'),
    url(r'^myproperties/$',views.myproperties, name='myproperties'),
    url(r'^(?P<product_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^properties/$',views.properties, name='properties'),
    #url(r'^(?P<id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^Edit_property/(?P<pk>[0-9]+)/$', views.edit, name='edit'),
    url(r'^localities/$',views.localities, name='localities'),
    url(r'^seeReviews/$',views.seeReviews, name='seeReviews'),
    url(r'^mustafaTown/$',views.mustafaTown, name='mustafaTown'),
    url(r'^iqbalTown/$',views.iqbalTown, name='iqbalTown'),
    url(r'^mustafaTown_properties/$',views.mustafaTown_properties, name='mustafaTown_properties'),
    url(r'^joharTown_properties/$',views.joharTown_properties, name='joharTown_properties'),
    url(r'^defence_properties/$',views.defence_properties, name='defence_properties'),
    url(r'^iqbalTown_rev/$',views.iqbalTown_rev, name='iqbalTown_rev'),
    url(r'^joharTown_rev/$',views.joharTown_rev, name='joharTown_rev'),
    url(r'^defence_rev/$',views.defence_rev, name='defence_rev'),
    url(r'^awan_rev/$',views.awan_rev, name='awan_rev'),
    url(r'^wapda_Rev/$',views.wapda_Rev, name='wapda_Rev'),
    url(r'^eden_rev/$',views.eden_rev, name='eden_rev'),
    url(r'^lake_rev/$',views.lake_rev, name='lake_rev'),
    url(r'^register/$',views.register,name='register'),
    url(r'^valueAddedServices/$',views.valueAddedServices,name='valueAddedServices'),
    url(r'^delete_property/(?P<product_id>[0-9]+)/$', views.delete, name='delete'),

]

simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r'^request_page/$',views.request_page, name='request_page'),
    url(r"^admin/", admin.site.urls),
    url(r"^myFYP/", include("myFYP.urls", namespace="myFYP")),
    url(r"^myFYP/", include("django.contrib.auth.urls")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/myFYP/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from myFYP.models import Products, Localities, Contact
from myFYP.models import UserProfileInfo
from django.contrib.auth.models import User
from django import forms
from django.core.validators import MinValueValidator,MaxValueValidator

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('profile_pic','type')


class ProductForm(forms.ModelForm):
    description = forms.CharField( widget=forms.Textarea)
    Rooms = forms.IntegerField(label='Rooms',
                    widget=forms.TextInput(attrs={'placeholder': 'No of Rooms'}))
    BathRooms = forms.IntegerField(label='BathRooms',
                    widget=forms.TextInput(attrs={'placeholder': 'No of BathRooms'}))

    class Meta():
        model = Products
        fields = '__all__'


class contactForm(forms.ModelForm):
    Message = forms.CharField( label='Entre Your Message along with your email:',
                              widget=forms.Textarea(attrs={'placeholder': 'Enter here...'}))
    email = forms.EmailField()
    class Meta():
        model = Contact
        fields = '__all__'




class LocalitiesForm(forms.ModelForm):
    description = forms.CharField( widget=forms.Textarea)
    rate_cleanliness = forms.IntegerField(min_value=0, max_value=5,
        label='Rate Cleanliness',
        widget=forms.NumberInput(attrs={'placeholder': 'Rate out of 5'})
    )
    rate_locality = forms.IntegerField(min_value=0, max_value=5,
        label='Rate locality',
        widget=forms.NumberInput(attrs={'placeholder': 'Rate out of 5'})
    )
    rate_security = forms.IntegerField(min_value=0, max_value=5,
        label='Rate security',
        widget=forms.NumberInput(attrs={'placeholder': 'Rate out of 5'})
    )
    rate_parks = forms.IntegerField(min_value=0, max_value=5,
        label='Rate parks',
        widget=forms.NumberInput(attrs={'placeholder': 'Rate out of 5'})
    )
    playGrounds = forms.IntegerField(min_value=0, max_value=5,
        label='Rate playGrounds',
        widget=forms.NumberInput(attrs={'placeholder': 'Rate out of 5'})
    )
    class Meta:
        model = Localities
        fields = '__all__'

simplesocial/myFYP/views.py
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView,TemplateView
from myFYP.models import Products,Localities,Contact,UserProfileInfo, User
from myFYP.forms import ProductForm,LocalitiesForm,contactForm, UserForm, UserProfileInfoForm
from django.shortcuts import get_object_or_404, redirect, reverse
from . import forms
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.core.mail import send_mail, BadHeaderError, EmailMessage
from django.contrib.messages import constants as messages
from django.http import HttpResponseForbidden, HttpResponseRedirect, Http404, HttpResponseNotFound, HttpResponse
from django.db.models import Avg, IntegerField

class Nointernet(TemplateView):
    template_name = "myFYP/nointernet.html"

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "myFYP/signup.html"


@login_required(login_url='/myFYP/signup/')
def delete(request, product_id):
    product = Products.objects.get(id=product_id)
    product.delete()
    #message.success(request,"deleted")
    return properties(request)



def contact(request):
    if request.method == 'POST':
        form = contactForm(request.POST,)
        if form.is_valid():
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            Phone_Number = form.cleaned_data['Phone_Number']
            message = form.cleaned_data['Message']
            name = form.cleaned_data['name']
            #form = [str(message)]
            #form = [message,'Phone_Number',Phone_Number, 'name',name]
            email = EmailMessage(subject,message,
                                     from_email,
                                     ['estatemerkez@gmail.com'],
                                     reply_to=[from_email])
            email.send()

            form = contactForm()
            return render(request, 'myFYP/contact.html', {
                'form': form
            })
            '''
            if subject and message and from_email:
                try:
                    send_mail(subject,
                              str(form),
                              from_email,
                              ['smackburg@gmail.com'],
                              fail_silently=False)
                    return contact(request)
                except BadHeaderError:
                    return HttpResponse('Invalid header found.')
                    '''
                #messages.success(request, 'Enquiry email successfully sent')
                #return render(request, 'myFYP/contact.html', {
                #    'form': form
                #})
            '''
            form.save()
            return contact(request)
            '''
    else:
        form = contactForm()
        return render(request, 'myFYP/contact.html', {
            'form': form
        })

class Addproperty(TemplateView):
    template_name = "myFYP/submit-property.html"


class About(TemplateView):
    template_name = "myFYP/about.html"

class Services(TemplateView):

    template_name = "myFYP/vas.html"

# class Main_login(TemplateView):
#     template_name = "myFYP/main_login.html"

@login_required(login_url='/myFYP/signup/')
def valueAddedServices(request):
    #users = User.objects.all()
    vas = UserProfileInfo.objects.select_related("user").all()
    return render(request, 'myFYP/services.html',{'vas':vas
                                                  })
@login_required(login_url='/myFYP/signup/')
def addproperty(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            emailad = current_user.email
            email = EmailMessage('Property Added ', 'You have just uploaded a property on our site EstateMerkez.com.The charges for per property upload is 500. if you pay this amount then your property will be displayed otherwise this will be removed by the adminself.for payment Contact : 03364738660 ',
                                 'estatemerkez@gmail.com',
                                 [emailad],
                                 reply_to=['estatemerkez@gmail.com'])
            email.send()
            form.save()
            return myproperties(request)
    else:
        form = ProductForm()
    return render(request, 'myFYP/submit-property.html', {
        'form': form
    })


def myproperties(request):
    try:
        products = Products.objects.all()
    except products.DoesNotExist:
        raise Http404("Property Does Not Exist")
    return render(request, 'myFYP/myproperties.html',{'products':products})

def iqbalTown(request):
    try:
        products = Products.objects.filter(location="iqbal town")
    except products.DoesNotExist:
        raise Http404("Property Does Not Exist")
    return render(request, 'myFYP/myproperties.html',{'products':products})

def mustafaTown_properties(request):
    try:
        products = Products.objects.filter(location="mustafa town")
    except products.DoesNotExist:
        raise Http404("Property Does Not Exist")
    return render(request, 'myFYP/myproperties.html',{'products':products})


def joharTown_properties(request):
    try:
        products = Products.objects.filter(location="johar town")
    except products.DoesNotExist:
        raise Http404("Property Does Not Exist")
    return render(request, 'myFYP/myproperties.html',{'products':products})


def defence_properties(request):
    try:
        products = Products.objects.filter(location="defence")
    except products.DoesNotExist:
        raise Http404("Property Does Not Exist")
    return render(request, 'myFYP/myproperties.html',{'products':products})


def detail(request ,product_id):
    try:
        product = Products.objects.get(id=product_id)
    except Products.DoesNotExist:
        return render(request, 'myFYP/404.html')
    return render(request, 'myFYP/propertydetail.html',{'product':product})

def properties(request):
    try:
        products = Products.objects.filter(user=request.user)
    except Products.DoesNotExist:
        raise Http404('This products does not exist')
    return render(request, 'myFYP/userProperties.html',{'products':products})

@login_required(login_url='/myFYP/signup/')
def edit(request,pk):
    template = 'myFYP/submit-property.html'
    products = get_object_or_404(Products, pk=pk)

    if request.method == 'POST':
        form = ProductForm(request.POST,request.FILES, instance=products)

        try:
            if form.is_valid():
                form.save()
                return properties(request)
        except Exception as e:
            messages.warning(request,'your post not saved as an error : {}'.format(e));
    else:
        form = ProductForm(instance=products)

    context = {
        'form' : form,
        'products' : products,
    }
    return render(request, template, context)

@login_required(login_url='/myFYP/signup/')
def localities(request):
    form = LocalitiesForm()

    if request.method == "POST":
        form = LocalitiesForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return seeReviews(request)
        else:
            return contact(request)
    return render(request, 'myFYP/addLocality.html',{'form': form})

def seeReviews(request):
    reviews1 = Localities.objects.filter(location="mustafa town")
    average1 = reviews1.aggregate(average1=Avg('rate_locality' , output_field=IntegerField()))

    reviews2 = Localities.objects.filter(location="johar town")
    average2 = reviews2.aggregate(average2=Avg('rate_locality', output_field=IntegerField()))

    reviews3 = Localities.objects.filter(location="iqbal town")
    average3 = reviews3.aggregate(average3=Avg('rate_locality', output_field=IntegerField()))

    reviews4 = Localities.objects.filter(location="defence")
    average4 = reviews4.aggregate(average4=Avg('rate_locality', output_field=IntegerField()))

    reviews5 = Localities.objects.filter(location="Awan town")
    average5 = reviews5.aggregate(average5=Avg('rate_locality', output_field=IntegerField()))

    reviews6 = Localities.objects.filter(location="Wapda town")
    average6 = reviews6.aggregate(average6=Avg('rate_locality', output_field=IntegerField()))

    reviews7 = Localities.objects.filter(location="Eden")
    average7 = reviews7.aggregate(average7=Avg('rate_locality', output_field=IntegerField()))

    reviews8 = Localities.objects.filter(location="Lake city")
    average8 = reviews8.aggregate(average8=Avg('rate_locality', output_field=IntegerField()))


    return render(request, 'myFYP/localities.html',{'average1' : average1 , 'average2' : average2 ,
                                                    'average3' : average3 , 'average4' : average4 ,
                                                    'average5' : average5 , 'average6' : average6 ,
                                                    'average7' : average7 , 'average8' : average8 ,
                                                    })

def mustafaTown(request):
    reviews = Localities.objects.filter(location="mustafa town")

    average = reviews.aggregate(average=Avg('rate_locality', output_field=IntegerField()))
    parks = reviews.aggregate(parks=Avg('rate_parks', output_field=IntegerField()))
    security = reviews.aggregate(security=Avg('rate_security', output_field=IntegerField()))
    cleanliness = reviews.aggregate(cleanliness=Avg('rate_cleanliness', output_field=IntegerField()))
    playgrounds = reviews.aggregate(playgrounds=Avg('playGrounds', output_field=IntegerField()))

    return render(request, 'myFYP/detailedReview.html',{'reviews': reviews , 'average' : average ,

simplesocial/myFYP/templates/myFYP/Contact_to_provider.html
{% extends "myFYP/header.html"%}
{% load staticfiles %}
{% block content %}
<!-- Sub banner start -->
<div class="sub-banner">
    <div class="overlay">
        <div class="container">
            <div class="breadcrumb-area">
                <h1>Contact to Service Provider</h1>
                <ul class="breadcrumbs">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Contact to Provider</li>
                </ul>
            </div>
        </div>
    </div>
</div>

    <div class="contact-body content-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!-- Contact form start -->
                <div class="contact-form">
                    <div class="main-title-2">
                        <h1><span>Contact</span></h1>
                    </div>
                    <form id="contact_form" action="" method="post" enctype="">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group fullname">
                                    <input type="text" name="full-name" class="input-text" disabled="disabled" placeholder="Full Name">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group enter-email">
                                    <input type="email" name="email" class="input-text" disabled="disabled" placeholder="Enter email">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group subject">
                                    <input type="text" name="subject" class="input-text" placeholder="Subject">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group number">
                                    <input type="text" name="phone" class="input-text" disabled="disabled" placeholder="Phone Number">
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 clearfix">
                                <div class="form-group message">
                                    <textarea class="input-text" name="message" placeholder="Write message"></textarea>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-6 col-sm-12 col-xs-12">
                                <div class="form-group send-btn">
                                    <button type="submit" class="button-md button-theme">Send Message</button>
                                </div>
                            </div>
                        </div>
                    </form>     
                </div>
                <!-- Contact form end -->
            </div>
            
        </div>
    </div>
</div>
    


<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB0N5pbJN10Y1oYFRd0MJ_v2g8W2QT74JE"></script>
<script>
    function LoadMap(propertes) {
        var defaultLat = 40.7110411;
        var defaultLng = -74.0110326;
        var mapOptions = {
            center: new google.maps.LatLng(defaultLat, defaultLng),
            zoom: 15,
            scrollwheel: false,
            styles: [
                {
                    featureType: "administrative",
                    elementType: "labels",
                    stylers: [
                        {visibility: "off"}
                    ]
                },
                {
                    featureType: "water",
                    elementType: "labels",
                    stylers: [
                        {visibility: "off"}
                    ]
                },
                {
                    featureType: 'poi.business',
                    stylers: [{visibility: 'off'}]
                },
                {
                    featureType: 'transit',
                    elementType: 'labels.icon',
                    stylers: [{visibility: 'off'}]
                },
            ]
        };
        var map = new google.maps.Map(document.getElementById("map"), mapOptions);
        var infoWindow = new google.maps.InfoWindow();
        var myLatlng = new google.maps.LatLng(40.7110411, -74.0110326);

        var marker = new google.maps.Marker({
            position: myLatlng,
            map: map
        });
        (function (marker) {
            google.maps.event.addListener(marker, "click", function (e) {
                infoWindow.setContent("" +
                    "<div class='map-properties contact-map-content'>" +
                    "<div class='map-content'>" +
                    "<p class='address'>123 Kathal St. Tampa City, </p>" +
                    "<ul class='map-properties-list'> " +
                    "<li><i class='fa fa-phone'></i>  +0477 8556 552</li> " +
                    "<li><i class='fa fa-envelope'></i>  info@themevessel.com</li> " +
                    "<li><a href='index.html'><i class='fa fa-globe'></i>  http://http://themevessel.com</li></a> " +
                    "</ul>" +
                    "</div>" +
                    "</div>");
                infoWindow.open(map, marker);
            });
        })(marker);
    }
    LoadMap();
</script>
{% endblock %}

simplesocial/myFYP/templates/myFYP/Signup_vas.html
{% extends "header.html"%}
{% load staticfiles %}
{% block content %}
{% load widget_tweaks %}
<div class="content">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Form content box start -->
                <div class="form-content-box">
                  {% if registered %}
                  <h1>Thank you for registering!</h1>
                {% else %}
                  <h1>Register Here</h1>
                  <h3>Just fill out the form.</h3>

                  <form enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    {% for hidden in user_form.hidden_fields %}
                      {{ hidden }}
                    {% endfor %}

                    {% for field in user_form.visible_fields %}
                      <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}

                        {% for error in field.errors %}
                          <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% endfor %}

                    {% for field in profile_form.visible_fields %}
                      <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field|add_class:'form-control' }}

                        {% for error in field.errors %}
                          <span class="help-block">{{ error }}</span>
                        {% endfor %}
                      </div>
                    {% endfor %}

                    <input type="submit" name="" value="Register">
                    <br>
                    <br>
                  </form>

                {% endif %}

                        <!-- Form end-->
                    </div>
                    <!-- Footer -->
                    <div class="footer">
                        <span>
                            I want to <a href="{% url 'myFYP:login' %}">return to login</a>

                        </span>
                    </div>
                </div>
                <!-- Form content box end -->
            </div>
        </div>
    </div>
</div>
<!-- Content area end -->
{% endblock %}

simplesocial/myFYP/templates/myFYP/detailedReview.html
{% extends "header.html"%}
{% load staticfiles %}
{% block content %}
<div class="sub-banner">
    <div class="overlay">
        <div class="container">
            <div class="breadcrumb-area">
                <h1>REVIEWS OF LOCALITY</h1>
                <ul class="breadcrumbs">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">REVIEWS OF LOCALITY</li>
                </ul>
            </div>
        </div>
    </div>
</div>

   <div class="content-area featured-properties">
    <div class="container">
        <!-- Main title -->
        <div class="main-title">
            <h1>Overall {{Name.average}} rating of this Location: {{ average.average }}</h1>
        </div>
        <div class="row">
            <div class="filtr-container">
                <div class="well">
    <table class="table">
      <thead>
        <tr>
          <th>Location<p></p></th>
          <th>Locality <p style="color : green">(avg ≈ {{ average.average }})</p></th>
          <th>Cleanliness <p style="color : green">(avg ≈ {{ cleanliness.cleanliness }})</p></th>
          <th>Security <p style="color : green">(avg ≈ {{ security.security }})</p></th>
          <th>Parks <p style="color : green">(avg ≈ {{ parks.parks }})</p></th>
          <th>play grounds <p style="color : green">(avg ≈ {{ playgrounds.playgrounds }})</p></th>
          <th>Description<p></p></th>
          <th>Review Date<p></p></th>

        </tr>
      </thead>
      <tbody>

        {% for rev in reviews %}
        <tr>
          <td>
            <b>{{rev.location}}</b>
        </td>
          <td>{{ rev.rate_locality }} out of 5

          </td>
          <td>{{ rev.rate_cleanliness }} out of 5</td>
          <td>{{ rev.rate_security }} out of 5</td>
          <td>{{rev.rate_parks}} out of 5</td>
          <td>{{rev.playGrounds}} out of 5</td>
          <td>{{rev.description}}</td>
          <td>{{ rev.uploaded_At }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

            </div>
        </div>
       </div>
    </div>
{% endblock %}

simplesocial/myFYP/templates/myFYP/login.html
{% extends "header.html"%}
{% load staticfiles %}
{% load bootstrap3 %}
 {% block content %}

<!-- Content area start -->
<div class="content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Form content box start -->
                <div class="form-content-box">
                    <!-- details -->
                    <div class="details">
                        <!-- Main title -->
                        <div class="main-title">
                            <h1><span>Login</span></h1>
                        </div>
                        <!-- Form start -->
          <form method="post" action="">

          {% csrf_token %}
          {% bootstrap_form form %}
            <button type="submit" class="search-button" >login</button>

        </form>
                        <!-- Form end -->
                    </div>
                    <!-- Footer -->
                    <div class="footer">
                        <span>
                            Don't have an account yet? <a href="{% url 'myFYP:signup' %}">Sign up now</a>
                        </span>
                    </div>
                </div>
                <!-- Form content box end -->
            </div>
        </div>
    </div>
</div>
<!-- Content area end -->
{% endblock %}

simplesocial/myFYP/templates/myFYP/temp.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

  </body>
</html>

simplesocial/myFYP/templates/myFYP/vas.html
{% extends "header.html"%}
{% load staticfiles %}
{% block content %}
<!-- Sub banner start -->
<div class="sub-banner">
    <div class="overlay">
        <div class="container">
            <div class="breadcrumb-area">
                <h1>Our Value Added Services</h1>
                <ul class="breadcrumbs">

                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Sub Banner end -->

<div class="about-city-estate">
    <div class="container">
        <div class="row">


                <div class="sidebar-widget clearfix biography">
                    <!-- Main Title 2 -->
                    <div class="main-title-2">
                        <h1><span>About our Service Providers</span></h1>
                    </div>
                    <p>
					Value-added services are additional benefits consumers can receive when they come to our platform.
					They are "add-ons" that can go a long way toward building good will if free, or can significantly increase revenue if offered for a discounted price to customers.
					Estate Merkez aims to provide high quality services that no one is providing <u>YET</u>.
                    </p>
                    <p>
					The Service Providers that are residing on our platform are:
                        </p>
						<ul>
						<li> Interior Designers</li>
						<li> Architecture Engineers</li>
						<li> Home Valuation Service Providers</li>
						</ul>

                    <br>

					<center>
                       <div class="col-xs-12 col-sm-6 col-md-12 col-lg-12">
					<center><h1>If you are a service provider? </h1></center>
                        <ul>

							<br>

							<class="nav navbar-nav">

              {% if not user.is_anonymous %}
              <p>If your are not seeing the link for your registration then you must logout first</p>
              {%endif%}
              {% if user.is_anonymous %}
                        <a href="{% url 'myFYP:register' %}" class="sign-in"><i class="fa fa-user"></i> Join Our Platform Today</a>
                        {% endif %}
                        </ul>

                    </div>
					</center>
                </div>
				</div>
				</div>
				</div>


 {% endblock %}

simplesocial/myFYP/templates/myFYP/vas_login.html
{% extends "header.html"%}
{% load staticfiles %}
{% load bootstrap3 %}
 {% block content %}

<!-- Content area start -->
<div class="content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- Form content box start -->
                <div class="form-content-box">
                    <!-- details -->
                    <div class="details">
                        <!-- Main title -->
                        <div class="main-title">
                            <h1><span>Login</span></h1>
                        </div>
                        <!-- Form start -->
          <form method="post" action="">

          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" value="Login" class="btn btn-default">

        </form>
                        <!-- Form end -->
                    </div>
                    <!-- Footer -->
                    <div class="footer">
                        <span>
                            Don't have an account yet? <a href="{% url 'myFYP:signup' %}">Sign up now</a>
                        </span>
                    </div>
                </div>
                <!-- Form content box end -->
            </div>
        </div>
    </div>
</div>
<!-- Content area end -->
{% endblock %}