simplesocial/myFYP/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'myFYP'
urlpatterns = [
    url(r"^login/$", auth_views.LoginView.as_view(template_name="myFYP/login.html"),name='login'),
    url(r"^vas_login/$", auth_views.LoginView.as_view(template_name="myFYP/vas_login.html"),name='vas_login'),
	url(r'^contact/$',views.contact, name='contact'),
    url(r"^logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"^signup/$", views.SignUp.as_view(), name="signup"),
	url(r'^addproperty/$',views.addproperty, name='addproperty'),
    url(r'^About-Us/$',views.About.as_view(), name='About-Us'),
    url(r'^services/$',views.Services.as_view(), name='Our-Services'),
    url(r'^nointernet/$',views.Nointernet.as_view(), name='nointernet'),
    # url(r'^main_login/$',views.Main_login.as_view(),name='main_login'),
    url(r'^myproperties/$',views.myproperties, name='myproperties'),
    url(r'^(?P<product_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^properties/$',views.properties, name='properties'),
    #url(r'^(?P<id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^Edit_property/(?P<pk>[0-9]+)/$', views.edit, name='edit'),
    url(r'^localities/$',views.localities, name='localities'),
    url(r'^seeReviews/$',views.seeReviews, name='seeReviews'),
    url(r'^mustafaTown/$',views.mustafaTown, name='mustafaTown'),
    url(r'^iqbalTown/$',views.iqbalTown, name='iqbalTown'),
    url(r'^mustafaTown_properties/$',views.mustafaTown_properties, name='mustafaTown_properties'),
    url(r'^joharTown_properties/$',views.joharTown_properties, name='joharTown_properties'),
    url(r'^defence_properties/$',views.defence_properties, name='defence_properties'),
    url(r'^iqbalTown_rev/$',views.iqbalTown_rev, name='iqbalTown_rev'),
    url(r'^joharTown_rev/$',views.joharTown_rev, name='joharTown_rev'),
    url(r'^defence_rev/$',views.defence_rev, name='defence_rev'),
    url(r'^awan_rev/$',views.awan_rev, name='awan_rev'),
    url(r'^wapda_Rev/$',views.wapda_Rev, name='wapda_Rev'),
    url(r'^eden_rev/$',views.eden_rev, name='eden_rev'),
    url(r'^lake_rev/$',views.lake_rev, name='lake_rev'),
    url(r'^register/$',views.register,name='register'),
    url(r'^valueAddedServices/$',views.valueAddedServices,name='valueAddedServices'),
    url(r'^delete_property/(?P<product_id>[0-9]+)/$', views.delete, name='delete'),

]

simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^test/$", views.TestPage.as_view(), name="test"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r'^request_page/$',views.request_page, name='request_page'),
    url(r"^admin/", admin.site.urls),
    url(r"^myFYP/", include("myFYP.urls", namespace="myFYP")),
    url(r"^myFYP/", include("django.contrib.auth.urls")),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplesocial/templates/test.html
{% extends "header.html" %}
{% block content %}
<div class="container">
  <div class="content-area">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                  <!-- Form content box start -->

                      <!-- details -->
                      <div class="details">
<center>  <h1>You are now logged in!</h1></center>
  <center> <h2><a  class="btn button-md border-button-theme" data-animation="animated fadeInUp delay-05s" href="{% url 'myFYP:addproperty'%}">Go to submit your property</a></h2></center>

</div>
</div>
</div>
</div>
</div>
</div>



{% endblock %}

simplesocial/templates/thanks.html
{% extends "header.html" %}
{% block content %}

<div class="container">
  <div class="content-area">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
<center><h1>Thanks for visiting! Come back soon!</h1></center>
</div>
</div>
</div>
</div>
</div>

{% endblock %}